### ISSUE TITLE
Issue with new log4j 

### ISSUE THREAD

**Issue by KurumiFake** [KurumiFake/Sustopia#1]
Weird crash, reverting the log4j patch fixes it but...
![Screenshot_2021-12-22-14-52-01-33](https://user-images.githubusercontent.com/86518350/147055975-89e868e7-e5a5-4c41-b6d5-06c0b47c3045.png)

**Comment by Meowohhh** [comment]
burh:6
-HoangBarell-

**Comment by KurumiFake** [comment]
Seems to be upstream's issue, will close this for now cuz i did the dummest way to resolv this
